/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradingViewRouteImport } from './routes/trading-view'
import { Route as OptionChainRouteImport } from './routes/option-chain'
import { Route as MarketMonitorRouteImport } from './routes/market-monitor'
import { Route as FileAnalysisRouteImport } from './routes/file-analysis'
import { Route as AiSignalsRouteImport } from './routes/ai-signals'
import { Route as AiBrainRouteImport } from './routes/ai-brain'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOptionChainRouteImport } from './routes/api/option-chain'
import { Route as ApiMarketDataRouteImport } from './routes/api/market-data'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'

const TradingViewRoute = TradingViewRouteImport.update({
  id: '/trading-view',
  path: '/trading-view',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionChainRoute = OptionChainRouteImport.update({
  id: '/option-chain',
  path: '/option-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketMonitorRoute = MarketMonitorRouteImport.update({
  id: '/market-monitor',
  path: '/market-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const FileAnalysisRoute = FileAnalysisRouteImport.update({
  id: '/file-analysis',
  path: '/file-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSignalsRoute = AiSignalsRouteImport.update({
  id: '/ai-signals',
  path: '/ai-signals',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBrainRoute = AiBrainRouteImport.update({
  id: '/ai-brain',
  path: '/ai-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOptionChainRoute = ApiOptionChainRouteImport.update({
  id: '/api/option-chain',
  path: '/api/option-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketDataRoute = ApiMarketDataRouteImport.update({
  id: '/api/market-data',
  path: '/api/market-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-brain': typeof AiBrainRoute
  '/ai-signals': typeof AiSignalsRoute
  '/file-analysis': typeof FileAnalysisRoute
  '/market-monitor': typeof MarketMonitorRoute
  '/option-chain': typeof OptionChainRoute
  '/trading-view': typeof TradingViewRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/market-data': typeof ApiMarketDataRoute
  '/api/option-chain': typeof ApiOptionChainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-brain': typeof AiBrainRoute
  '/ai-signals': typeof AiSignalsRoute
  '/file-analysis': typeof FileAnalysisRoute
  '/market-monitor': typeof MarketMonitorRoute
  '/option-chain': typeof OptionChainRoute
  '/trading-view': typeof TradingViewRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/market-data': typeof ApiMarketDataRoute
  '/api/option-chain': typeof ApiOptionChainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-brain': typeof AiBrainRoute
  '/ai-signals': typeof AiSignalsRoute
  '/file-analysis': typeof FileAnalysisRoute
  '/market-monitor': typeof MarketMonitorRoute
  '/option-chain': typeof OptionChainRoute
  '/trading-view': typeof TradingViewRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/market-data': typeof ApiMarketDataRoute
  '/api/option-chain': typeof ApiOptionChainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-brain'
    | '/ai-signals'
    | '/file-analysis'
    | '/market-monitor'
    | '/option-chain'
    | '/trading-view'
    | '/api/ai-chat'
    | '/api/market-data'
    | '/api/option-chain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-brain'
    | '/ai-signals'
    | '/file-analysis'
    | '/market-monitor'
    | '/option-chain'
    | '/trading-view'
    | '/api/ai-chat'
    | '/api/market-data'
    | '/api/option-chain'
  id:
    | '__root__'
    | '/'
    | '/ai-brain'
    | '/ai-signals'
    | '/file-analysis'
    | '/market-monitor'
    | '/option-chain'
    | '/trading-view'
    | '/api/ai-chat'
    | '/api/market-data'
    | '/api/option-chain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiBrainRoute: typeof AiBrainRoute
  AiSignalsRoute: typeof AiSignalsRoute
  FileAnalysisRoute: typeof FileAnalysisRoute
  MarketMonitorRoute: typeof MarketMonitorRoute
  OptionChainRoute: typeof OptionChainRoute
  TradingViewRoute: typeof TradingViewRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiMarketDataRoute: typeof ApiMarketDataRoute
  ApiOptionChainRoute: typeof ApiOptionChainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trading-view': {
      id: '/trading-view'
      path: '/trading-view'
      fullPath: '/trading-view'
      preLoaderRoute: typeof TradingViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/option-chain': {
      id: '/option-chain'
      path: '/option-chain'
      fullPath: '/option-chain'
      preLoaderRoute: typeof OptionChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-monitor': {
      id: '/market-monitor'
      path: '/market-monitor'
      fullPath: '/market-monitor'
      preLoaderRoute: typeof MarketMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-analysis': {
      id: '/file-analysis'
      path: '/file-analysis'
      fullPath: '/file-analysis'
      preLoaderRoute: typeof FileAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-signals': {
      id: '/ai-signals'
      path: '/ai-signals'
      fullPath: '/ai-signals'
      preLoaderRoute: typeof AiSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-brain': {
      id: '/ai-brain'
      path: '/ai-brain'
      fullPath: '/ai-brain'
      preLoaderRoute: typeof AiBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/option-chain': {
      id: '/api/option-chain'
      path: '/api/option-chain'
      fullPath: '/api/option-chain'
      preLoaderRoute: typeof ApiOptionChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-data': {
      id: '/api/market-data'
      path: '/api/market-data'
      fullPath: '/api/market-data'
      preLoaderRoute: typeof ApiMarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiBrainRoute: AiBrainRoute,
  AiSignalsRoute: AiSignalsRoute,
  FileAnalysisRoute: FileAnalysisRoute,
  MarketMonitorRoute: MarketMonitorRoute,
  OptionChainRoute: OptionChainRoute,
  TradingViewRoute: TradingViewRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiMarketDataRoute: ApiMarketDataRoute,
  ApiOptionChainRoute: ApiOptionChainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
